# Generated by Django 5.2.4 on 2025-08-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
