# Generated by Django 5.2.4 on 2025-08-11 03:39

from django.db import migrations



def cargar_categorias(apps, schema_editor):
    Category = apps.get_model('app', 'Category')
    categorias = [
        ('Inteligencia Artificial', 'ia'),
        ('Robotica', 'robot'),
        ('Opiniónes', 'opinion'),
        ('Gaming', 'games'),
        ('Otros', 'others'),
    ]
    for titulo, slug in categorias:
        Category.objects.get_or_create(titulo=titulo, slug=slug)

class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_category_slug_alter_category_titulo'),
    ]

    operations = [
    ]