# Generated by Django 5.2.4 on 2025-08-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
